Repository 7-umc-GrowIT/GrowIT-SpringBoot, pull requests merged in 2025-02, with the labels that each got.

#139 [#110] Feat: 카카오 로그인 API - 인가 코드로 토큰 발급
  build.gradle
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/config/SecurityConfig.java
  src/main/java/umc/GrowIT/Server/config/WebClientConfig.java
  src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoService.java
  src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/TestController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/OAuthDTO/OAuthResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/KakaoResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
Labels: ✨ feature

#141 [#140] CORS 설정
  src/main/java/umc/GrowIT/Server/config/SecurityConfig.java
  src/main/java/umc/GrowIT/Server/config/WebConfig.java
  src/main/java/umc/GrowIT/Server/jwt/CustomAuthenticationEntryPoint.java
Labels: ⚙️ setting

#145 [#144] Refactor: 챌린지 현황 조회 메서드 및 쿼리문 수정
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
Labels: 🔨 refactor

#138 [#137] Bug: JWT 인증 필터 예외 처리
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationFilter.java
Labels: 🐞 bug

#149 [#143] Feat: 챌린지 인증 이미지 첨부(S3 활용)
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/ImageHandler.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ImageService/ImageService.java
  src/main/java/umc/GrowIT/Server/utils/ImageUtils.java
  src/main/java/umc/GrowIT/Server/utils/SecurityUtils.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ImageDTO/UploadImageResponse.java
Labels: ✨ feature

#131 [#129] Feat : 그로 아이템 착용/해제 api & 아이템 착용용 이미지기능 추가
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/domain/UserItem.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipRequestDTO.java
Labels: ✨ feature, 🔨 refactor

#136 [#64] Feat: 선택한 챌린지 저장 API
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#153 [#135] Refactor : 착용용 이미지 응답 추가 및 이미지url 전달방식 수정
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
Labels: 🔨 refactor

#157 [#155] Refactor: 선택한 챌린지 저장 API 수정
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature, 🔨 refactor

#163 [#160] Refactor: 그로&착용 아이템 이미지 조회 API 수정
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
Labels: 🔨 refactor

#169 [#162] Feat : Gro 생성시에 핑크색 PLANT 설정 추가
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
Labels: ✨ feature

#171 [#164] Feat: 챌린지 추천 API 구현
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/KeywordHandler.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/OpenAIHandler.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/converter/KeywordConverter.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeKeywordRepository.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/KeywordRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/KeywordDTO/KeywordResponseDTO.java
Labels: ✨ feature

#159 [#150] Refactor: 챌린지 홈 조회 응답 결과 수정
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeKeywordRepository.java
  src/main/java/umc/GrowIT/Server/repository/KeywordRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/KeywordService/KeywordService.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: 🔨 refactor

#174 [#167] Feat: 파인튜닝 AI 적용
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/dto/OpenAIDTO/ChatGPTRequest.java
  src/main/java/umc/GrowIT/Server/web/dto/OpenAIDTO/Message.java
Labels: ✨ feature

#175 [#173] Refactor: 챌린지 추천 API 수정 (->일기 분석 API)
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/domain/DiaryKeyword.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🔨 refactor

#183 [#180] Feat: 챌린지 인증 작성 시 유저 크레딧 개수 증가
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/util/ImageUtils.java
  src/main/java/umc/GrowIT/Server/util/SecurityUtils.java
Labels: ✨ feature

#191 [#184] Refactor : 기본PLANT 변경 및 그로 예외처리
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/repository/GroRepository/GroRepository.java
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
  src/test/resources/application.yml
Labels: 🔨 refactor

#193 [#192] Refactor: 일기 분석 API 수정
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🔨 refactor

#195 [#194] Refactor: 챌린지 인증 내역 조회 certificationDate 수정
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: 🔨 refactor

#197 [#196] Feat: 스케줄러 - 오래된 인증번호 삭제
  src/main/java/umc/GrowIT/Server/GrowItServerApplication.java
  src/main/java/umc/GrowIT/Server/repository/AuthenticationCodeRepository.java
  src/main/java/umc/GrowIT/Server/scheduler/Scheduler.java
Labels: ✨ feature

#204 [#202] Fix: 음성 일기, 일기 요약 API 프롬프트 수정
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🐞 bug

#203 [#200] Refactor: 챌린지 관련 코드 수정
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: 🔨 refactor

#207 [#206] Fix: 날짜 검사 부분 제거
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
Labels: 🐞 bug

#208 [#205] Setting: HTTPS 적용
  .gitignore
Labels: ⚙️ setting

#210 [#201] Fix: 일기 분석 API - 플라스크 연결
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/FlaskHandler.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
Labels: 🐞 bug

#212 [#211] Refactor: 일기 분석 API - 플라스크 연결 수정
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🔨 refactor

#215 [#170] ci/cd 워크플로우 최적화
  .github/workflows/dev_deploy.yml
  src/test/java/umc/GrowIT/Server/GrowItServerApplicationTests.java
  src/test/resources/application.yml
Labels: 🔨 refactor, ⚙️ setting

#216 [#209] Refactor: 챌린지 홈 조회 시 recommendedChallenges 업데이트
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeKeywordRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
Labels: 🔨 refactor

#218 [#217] Refactor: 인증 메일 템플릿 보완
  src/main/resources/templates/email-authentication.html
Labels: 🔨 refactor

#222 [#219] Refactor: 챌린지 date 필드 추가
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
Labels: 🔨 refactor

#226 [#223] Feat: 일기 삭제 API에서 관련된 UserChallenger 삭제 기능 추가
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: ✨ feature

#213 Update README.md
  AI대화화면.jpg
  README.md
  그로꾸미기화면.jpg
  그로우잇 아키텍처 다이어그램.jpg
  일기요약화면.jpg
  챌린지인증화면.jpg
  챌린지추천화면.jpg
Labels: 📝 docs

#228 [#221] Feat: 회원탈퇴 스케줄러 & 캐스케이드 설정
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/Diary.java
  src/main/java/umc/GrowIT/Server/domain/DiaryKeyword.java
  src/main/java/umc/GrowIT/Server/domain/Gro.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/domain/OAuthAccount.java
  src/main/java/umc/GrowIT/Server/domain/RefreshToken.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/domain/UserItem.java
  src/main/java/umc/GrowIT/Server/domain/UserTerm.java
  src/main/java/umc/GrowIT/Server/repository/RefreshTokenRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserRepository.java
  src/main/java/umc/GrowIT/Server/scheduler/Scheduler.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
Labels: ✨ feature
