Repository 7-umc-GrowIT/GrowIT-SpringBoot, pull requests merged in 2025-01, with the labels that each got.

#2 [#1] Chore: Swagger 설정
  build.gradle
  src/main/java/umc/GrowIT/Server/config/SwaggerConfig.java
Labels: ⚙️ setting

#9 [#8] Fix: Swagger 버전 변경
  build.gradle
Labels: 🐞 bug

#18 [#16] Feat: 일기 관련 API 명세서 작성
  src/main/java/umc/GrowIT/Server/web/controller/DiaryRestController.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryResponseDTO.java
Labels: ✨ feature

#17 [#7] Feat: 아이템/Gro관련 Entity 및 API Swagger관련기능 생성
  build.gradle
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/domain/Gro.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/domain/RefreshToken.java
  src/main/java/umc/GrowIT/Server/domain/Term.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/domain/UserItem.java
  src/main/java/umc/GrowIT/Server/domain/UserTerm.java
  src/main/java/umc/GrowIT/Server/domain/common/BaseEntity.java
  src/main/java/umc/GrowIT/Server/domain/enums/ItemCategory.java
  src/main/java/umc/GrowIT/Server/domain/enums/ItemStatus.java
  src/main/java/umc/GrowIT/Server/domain/enums/Provider.java
  src/main/java/umc/GrowIT/Server/domain/enums/TermType.java
  src/main/java/umc/GrowIT/Server/domain/enums/UserStatus.java
  src/main/java/umc/GrowIT/Server/web/controller/GroController.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/dto/CreditDTO/CreditResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/PaymentDTO/PaymentRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/PaymentDTO/PaymentResponseDTO.java
Labels: ✨ feature

#22 [#19] Feat : 카테고리별 아이템 조회 API기능 구현
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryCustom.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryImpl.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryService.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
Labels: ✨ feature

#24 [#14] Feat: 아이템 구매/설정 관련 API
  src/main/java/umc/GrowIT/Server/controller/User2Controller.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java
  src/main/java/umc/GrowIT/Server/web/controller/HomeRestController.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemRestController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserRestController.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/HomeDTO/HomeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
Labels: ✨ feature, 📝 docs

#28 [#27] Refactor: 일기 제목부분 제거 및 수정
  src/main/java/umc/GrowIT/Server/domain/Diary.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryRestController.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🔨 refactor

#29 [#20] Feat: 챌린지 관련 API 명세서 작성
  src/main/java/umc/GrowIT/Server/converter/UserConverter.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/repository/UserRepository.java
  src/main/java/umc/GrowIT/Server/service/UserCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#34 [#23] 크레딧 조회 관련 API 구현
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/CreditConverter.java
  src/main/java/umc/GrowIT/Server/repository/CreditRepository/CreditRepository.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryCustom.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryImpl.java
  src/main/java/umc/GrowIT/Server/service/CreditService/CreditQueryService.java
  src/main/java/umc/GrowIT/Server/service/CreditService/CreditQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryService.java
  src/main/java/umc/GrowIT/Server/web/controller/GroController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/dto/CreditDTO/CreditResponseDTO.java
Labels: ✨ feature

#35 [#33] Feat: 챌린지 현황 조회(완료/미완료) API 구현
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/enums/ChallengeType.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#39 [#38] Feat: 챌린지 현황(랜덤, 데일리) 조회 API 구현
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#46 [#45] Feat : Item, Gro, User Controller에 속한 API일부에 대한 Specification파일 작성
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/web/controller/GroController.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/GroSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
Labels: 🔨 refactor

#48 [#47] Refactor: /home & /users/password 관련 코드 삭제
  src/main/java/umc/GrowIT/Server/web/controller/HomeController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/HomeDTO/HomeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
Labels: 🔨 refactor

#55 [#54] Refactor: 일기 관련 API의 Specification 작성
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
Labels: 🔨 refactor

#57 [#56] Feat: 일기 작성 날짜 조회 API 구현
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
Labels: ✨ feature

#61 [#50] Feat: 회원탈퇴 API 개발
  src/main/java/umc/GrowIT/Server/converter/UserConverter.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/service/userService/UserCommandService.java
  src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
Labels: ✨ feature

#60 [#49] Feat: 챌린지 삭제 API 개발
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/ChallengeHandler.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#63 [#62] Feat: 아이템 구매 API 개발
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/apiPayload/exception/ItemHandler.java
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/domain/UserItem.java
  src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
Labels: ✨ feature

#69 [#66] Feat: 인증 메일 전송 API 개발
  .gitignore
  build.gradle
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/AuthenticationCodeConverter.java
  src/main/java/umc/GrowIT/Server/domain/AuthenticationCode.java
  src/main/java/umc/GrowIT/Server/domain/enums/AuthType.java
  src/main/java/umc/GrowIT/Server/domain/enums/CodeStatus.java
  src/main/java/umc/GrowIT/Server/repository/AuthenticationCodeRepository.java
  src/main/java/umc/GrowIT/Server/service/authService/AuthService.java
  src/main/java/umc/GrowIT/Server/service/authService/AuthServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
  src/main/resources/templates/email-authentication.html
Labels: ✨ feature

#43 [#40] Feat: 챌린지 인증 작성 API 구현
  src/main/java/umc/GrowIT/Server/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/domain/enums/ChallengeStatus.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
Labels: ✨ feature

#78 [#70] Feat: 인증번호 확인 API 개발
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/AuthenticationCodeConverter.java
  src/main/java/umc/GrowIT/Server/domain/AuthenticationCode.java
  src/main/java/umc/GrowIT/Server/repository/AuthenticationCodeRepository.java
  src/main/java/umc/GrowIT/Server/service/authService/AuthService.java
  src/main/java/umc/GrowIT/Server/service/authService/AuthServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthRequestDTO.java
Labels: ✨ feature

#83 [#65] Feat: 특정 일기 조회 API 구현
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
Labels: ✨ feature

#81 [#79] Feat: 토큰 재발급 API
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/TokenConverter.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java
  src/main/java/umc/GrowIT/Server/repository/RefreshTokenRepository.java
  src/main/java/umc/GrowIT/Server/service/authService/CustomUserDetailsService.java
  src/main/java/umc/GrowIT/Server/service/authService/UserCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/refreshToken/RefreshTokenCommandService.java
  src/main/java/umc/GrowIT/Server/service/refreshTokenService/RefreshTokenCommandService.java
  src/main/java/umc/GrowIT/Server/service/refreshTokenService/RefreshTokenCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/TestController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
Labels: ✨ feature

#86 [#84] Feat: 일기 수정하기 API 구현
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/domain/Diary.java
  src/main/java/umc/GrowIT/Server/domain/common/BaseEntity.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
Labels: ✨ feature

#91 [#72] Setting: S3 환경설정
  build.gradle
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/config/S3Config.java
Labels: ⚙️ setting

#93 [#90] Refactor: 일기를 작성하는 날짜 필드 추가
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/domain/Diary.java
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🔨 refactor

#104 [#88] Refactor: 챌린지 삭제 API 수정
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
Labels: 🐞 bug, 🔨 refactor, 📝 docs

#98 [#87] Setting: Security Config 설정 변경 및 토큰 만료 시간 변경
  .DS_Store
  src/main/java/umc/GrowIT/Server/config/SecurityConfig.java
  src/main/java/umc/GrowIT/Server/domain/Term.java
  src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/KakaoController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/KakaoSpecification.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
Labels: ⚙️ setting

#109 [#108] Refactor: JWT 토큰 발급 코드 리팩토링
  src/main/java/umc/GrowIT/Server/converter/TokenConverter.java
  src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java
Labels: 🔨 refactor

#111 [#105] Feat: 그로와 착용 아이템 이미지 조회 API 개발
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/GroConverter.java
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/repository/GroRepository/GroRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandService.java
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/GroController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/GroSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroResponseDTO.java
Labels: ✨ feature

#117 [#101] Feat: 일기 생성(수정 시) 날짜,글자 수 검사 기능 추가
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/domain/Diary.java
  src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
Labels: ✨ feature

#80 [#44] Feat: 챌린지 인증 내역 조회 API 구현
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#123 [#122] Feat : 상점 아이템 조회/보유중인 아이템 조회 api 관련코드 수정 및 요구사항 반영
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/domain/Item.java
  src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryService.java
  src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
Labels: ✨ feature, 🐞 bug

#119 [#118] Refactor: 일기 관련 API 명세서 수정
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🔨 refactor, 📝 docs

#128 [#127] Refactor: 그로 이미지 key값 수정
  src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
Labels: 🐞 bug, 🔨 refactor

#125 [#59] Feat: 챌린지 인증내용 수정 API
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/domain/Challenge.java
  src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
  src/main/java/umc/GrowIT/Server/domain/enums/UserChallengeType.java
  src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
  src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: ✨ feature

#134 [#133] Bug : 업로드 artifact버전 변경
  .github/workflows/dev_deploy.yml
Labels: 🐞 bug

#126 [#124] Bug: 탈퇴 회원 처리 (토큰 인증 필터 및 API 수정)
  src/main/java/umc/GrowIT/Server/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/config/SecurityConfig.java
  src/main/java/umc/GrowIT/Server/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/umc/GrowIT/Server/jwt/CustomUserDetails.java
  src/main/java/umc/GrowIT/Server/jwt/CustomUserDetailsService.java
  src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationException.java
  src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java
  src/main/java/umc/GrowIT/Server/service/authService/AuthServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoService.java
  src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/refreshTokenService/RefreshTokenCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/userService/UserCommandService.java
  src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/userService/UserQueryService.java
  src/main/java/umc/GrowIT/Server/service/userService/UserQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
Labels: 🐞 bug
