Repository 7-umc-GrowIT/GrowIT-SpringBoot, pull requests merged in 2025-09, with the labels that each got.

#290 [#288] Refactor: 챌린지 인증 작성 제한
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
  src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
Labels: 🔨 refactor

#297 [#289] Fix: CreditUtil 구현 및 일기 크레딧 악용 문제 해결
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
  src/main/java/umc/GrowIT/Server/converter/UserConverter.java
  src/main/java/umc/GrowIT/Server/domain/CreditHistory.java
  src/main/java/umc/GrowIT/Server/domain/User.java
  src/main/java/umc/GrowIT/Server/domain/enums/CreditSource.java
  src/main/java/umc/GrowIT/Server/domain/enums/CreditTransactionType.java
  src/main/java/umc/GrowIT/Server/repository/CreditHistoryRepository.java
  src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/itemService/ItemCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/userService/UserQueryService.java
  src/main/java/umc/GrowIT/Server/service/userService/UserQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/userService/UserWithdrawalServiceImpl.java
  src/main/java/umc/GrowIT/Server/util/CreditUtil.java
  src/main/java/umc/GrowIT/Server/web/controller/UserController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
Labels: ✨ feature, 🐞 bug

#304 [#303] Fix: 파일 경로에 따른 불필요한 임포트문 삭제
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
Labels: 🐞 bug

#312 Setting/#285 서버 로그 기록 세팅
  .gitignore
  src/main/resources/logback-spring.xml
Labels: ⚙️ setting

#314 [#313] Fix: 일기 작성 시 크레딧 미적립 문제 해결
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🐞 bug

#282 [#280] Feat : 약관 목록 조회 및 검증 로직 변경
  src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/GrowIT/Server/domain/Term.java
  src/main/java/umc/GrowIT/Server/repository/TermRepository.java
  src/main/java/umc/GrowIT/Server/service/termService/TermCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/termService/TermQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
Labels: ✨ feature

#322 [#299] Refactor: 일기 삭제 시, 사용자 챌린지는 삭제되지 않도록 수정
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeQueryServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🔨 refactor

#336 [#335] Refactor : 엑세스&리프레시 토큰 수명 수정
  src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
Labels: 🔨 refactor

#337 [#334] Refactor: CreditGrantResult 생성에 따른 챌린지 응답 수정
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/util/CreditUtil.java
Labels: 🔨 refactor

#348 [#347] Setting: AT&RT 만료시간 임시 변경
  src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
Labels: ⚙️ setting

#356 [#335] Bug : 소셜 간편가입 오류로 로그 추가
  src/main/java/umc/GrowIT/Server/service/oAuthService/OAuthCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/service/oAuthService/appleService/AppleServiceImpl.java
Labels: 🐞 bug

#370 [#369] Refactor: 챌린지 현황 조회 시 챌린지 내용 반환
  src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
  src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
Labels: 🔨 refactor

#377 [#376] refactor : 음성일기 글자 수 검토 로직 구현
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🔨 refactor

#389 [#388] Refactor: 기존 일기 저장 API 임시저장으로 변경
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/repository/DiaryRepository.java
  src/main/java/umc/GrowIT/Server/scheduler/Scheduler.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
  src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: ✨ feature, 🔨 refactor

#393 [#392] Refactor: 음성일기 임시저장 시 일기내용 반환
  src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
  src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
Labels: 🐞 bug, 🔨 refactor

#395 [#394] Refactor: 카테고리별 아이템 조회 시 가격 오름차순 정렬
  src/main/java/umc/GrowIT/Server/repository/ItemRepository.java
  src/main/java/umc/GrowIT/Server/service/itemService/ItemQueryServiceImpl.java
Labels: 🔨 refactor

#399 [#398] Fix: 챌린지 홈에서 일기 데이터 조회 시 COMPLETED 조건 추가
  src/main/java/umc/GrowIT/Server/repository/DiaryRepository.java
Labels: 🐞 bug

#403 [#401] Refactor : 일기 요약 gpt 모델 교체
  src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
Labels: 🔨 refactor

#421 [#420] Setting : CORS 설정 추가
  src/main/java/umc/GrowIT/Server/config/WebConfig.java
Labels: ⚙️ setting
